void drawStart()
{
    if (has_colors())
    {
        start_color();

        init_pair(1, COLOR_WHITE, COLOR_RED);
        init_pair(2, COLOR_WHITE, COLOR_YELLOW);
        init_pair(3, COLOR_WHITE, COLOR_GREEN);
        init_pair(4, COLOR_WHITE, COLOR_BLUE);
        init_pair(5, COLOR_WHITE, COLOR_BLACK);
        init_pair(6, COLOR_WHITE, COLOR_WHITE);

    }
    attron(COLOR_PAIR(1));

    //H
    move(5, 15);
    addstr(" ");
    move(6, 15);
    addstr(" ");
    move(7, 15);
    addstr(" ");
    move(8, 15);
    addstr(" ");
    move(9, 15);
    addstr(" ");

    move(5, 14);
    addstr(" ");
    move(6, 14);
    addstr(" ");
    move(7, 14);
    addstr(" ");
    move(8, 14);
    addstr(" ");
    move(9, 14);
    addstr(" ");

    move(7, 16);
    addstr(" ");
    move(7, 17);
    addstr(" ");
    move(7, 18);
    addstr(" ");

    move(5, 19);
    addstr(" ");
    move(6, 19);
    addstr(" ");
    move(7, 19);
    addstr(" ");
    move(8, 19);
    addstr(" ");
    move(9, 19);
    addstr(" ");

    move(5, 20);
    addstr(" ");
    move(6, 20);
    addstr(" ");
    move(7, 20);
    addstr(" ");
    move(8, 20);
    addstr(" ");
    move(9, 20);
    addstr(" ");

    //A
    move(5, 22);
    addstr(" ");
    move(6, 22);
    addstr(" ");
    move(7, 22);
    addstr(" ");
    move(8, 22);
    addstr(" ");
    move(9, 22);
    addstr(" ");
    move(5, 23);
    addstr(" ");
    move(6, 23);
    addstr(" ");
    move(7, 23);
    addstr(" ");
    move(8, 23);
    addstr(" ");
    move(9, 23);
    addstr(" ");

    move(5, 24);
    addstr(" ");
    move(5, 25);
    addstr(" ");
    move(5, 26);
    addstr(" ");
    move(7, 24);
    addstr(" ");
    move(7, 25);
    addstr(" ");
    move(7, 26);
    addstr(" ");

    move(5, 27);
    addstr(" ");
    move(6, 27);
    addstr(" ");
    move(7, 27);
    addstr(" ");
    move(8, 27);
    addstr(" ");
    move(9, 27);
    addstr(" ");
    move(5, 28);
    addstr(" ");
    move(6, 28);
    addstr(" ");
    move(7, 28);
    addstr(" ");
    move(8, 28);
    addstr(" ");
    move(9, 28);
    addstr(" ");

    //N
    move(5, 30);
    addstr(" ");
    move(6, 30);
    addstr(" ");
    move(7, 30);
    addstr(" ");
    move(8, 30);
    addstr(" ");
    move(9, 30);
    addstr(" ");
    move(5, 31);
    addstr(" ");
    move(6, 31);
    addstr(" ");
    move(7, 31);
    addstr(" ");
    move(8, 31);
    addstr(" ");
    move(9, 31);
    addstr(" ");

    move(5, 32);
    addstr(" ");
    move(6, 32);
    addstr(" ");
    move(6, 33);
    addstr(" ");
    move(7, 33);
    addstr(" ");
    move(7, 34);
    addstr(" ");
    move(8, 34);
    addstr(" ");
    move(8, 35);
    addstr(" ");
    move(9, 35);
    addstr(" ");
    move(9, 36);
    addstr(" ");

    move(8, 36);
    addstr(" ");
    move(7, 36);
    addstr(" ");
    move(6, 36);
    addstr(" ");
    move(5, 36);
    addstr(" ");
    move(9, 37);
    addstr(" ");
    move(8, 37);
    addstr(" ");
    move(7, 37);
    addstr(" ");
    move(6, 37);
    addstr(" ");
    move(5, 37);
    addstr(" ");

    //G
    move(5, 39);
    addstr(" ");
    move(6, 39);
    addstr(" ");
    move(7, 39);
    addstr(" ");
    move(8, 39);
    addstr(" ");
    move(9, 39);
    addstr(" ");
    move(5, 40);
    addstr(" ");
    move(6, 40);
    addstr(" ");
    move(7, 40);
    addstr(" ");
    move(8, 40);
    addstr(" ");
    move(9, 40);
    addstr(" ");

    move(5, 41);
    addstr(" ");
    move(5, 42);
    addstr(" ");
    move(5, 43);
    addstr(" ");
    move(5, 44);
    addstr(" ");
    move(9, 41);
    addstr(" ");
    move(9, 42);
    addstr(" ");
    move(9, 43);
    addstr(" ");
    move(9, 44);
    addstr(" ");
    move(7, 43);
    addstr(" ");
    move(7, 44);
    addstr(" ");

    move(5, 45);
    addstr(" ");
    move(7, 45);
    addstr(" ");
    move(8, 45);
    addstr(" ");
    move(9, 45);
    addstr(" ");
    move(5, 46);
    addstr(" ");
    move(7, 46);
    addstr(" ");
    move(8, 46);
    addstr(" ");
    move(9, 46);
    addstr(" ");

    attron(COLOR_PAIR(4));

    //M
    move(5, 48);
    addstr(" ");
    move(6, 48);
    addstr(" ");
    move(7, 48);
    addstr(" ");
    move(8, 48);
    addstr(" ");
    move(9, 48);
    addstr(" ");
    move(5, 49);
    addstr(" ");
    move(6, 49);
    addstr(" ");
    move(7, 49);
    addstr(" ");
    move(8, 49);
    addstr(" ");
    move(9, 49);
    addstr(" ");

    move(5, 50);
    addstr(" ");
    move(5, 51);
    addstr(" ");
    move(5, 52);
    addstr(" ");
    move(5, 53);
    addstr(" ");
    move(5, 54);
    addstr(" ");
    move(5, 55);
    addstr(" ");

    move(6, 52);
    addstr(" ");
    move(6, 53);
    addstr(" ");
    move(7, 52);
    addstr(" ");
    move(7, 53);
    addstr(" ");
    move(8, 52);
    addstr(" ");
    move(8, 53);
    addstr(" ");
    move(9, 52);
    addstr(" ");
    move(9, 53);
    addstr(" ");


    move(5, 56);
    addstr(" ");
    move(6, 56);
    addstr(" ");
    move(7, 56);
    addstr(" ");
    move(8, 56);
    addstr(" ");
    move(9, 56);
    addstr(" ");
    move(5, 57);
    addstr(" ");
    move(6, 57);
    addstr(" ");
    move(7, 57);
    addstr(" ");
    move(8, 57);
    addstr(" ");
    move(9, 57);
    addstr(" ");

    //A
    move(5, 59);
    addstr(" ");
    move(6, 59);
    addstr(" ");
    move(7, 59);
    addstr(" ");
    move(8, 59);
    addstr(" ");
    move(9, 59);
    addstr(" ");
    move(5, 60);
    addstr(" ");
    move(6, 60);
    addstr(" ");
    move(7, 60);
    addstr(" ");
    move(8, 60);
    addstr(" ");
    move(9, 60);
    addstr(" ");

    move(5, 61);
    addstr(" ");
    move(5, 62);
    addstr(" ");
    move(5, 63);
    addstr(" ");
    move(7, 61);
    addstr(" ");
    move(7, 62);
    addstr(" ");
    move(7, 63);
    addstr(" ");

    move(5, 64);
    addstr(" ");
    move(6, 64);
    addstr(" ");
    move(7, 64);
    addstr(" ");
    move(8, 64);
    addstr(" ");
    move(9, 64);
    addstr(" ");
    move(5, 65);
    addstr(" ");
    move(6, 65);
    addstr(" ");
    move(7, 65);
    addstr(" ");
    move(8, 65);
    addstr(" ");
    move(9, 65);
    addstr(" ");

    //N
    move(5, 67);
    addstr(" ");
    move(6, 67);
    addstr(" ");
    move(7, 67);
    addstr(" ");
    move(8, 67);
    addstr(" ");
    move(9, 67);
    addstr(" ");
    move(5, 68);
    addstr(" ");
    move(6, 68);
    addstr(" ");
    move(7, 68);
    addstr(" ");
    move(8, 68);
    addstr(" ");
    move(9, 68);
    addstr(" ");

    move(5, 69);
    addstr(" ");
    move(6, 69);
    addstr(" ");
    move(6, 70);
    addstr(" ");
    move(7, 70);
    addstr(" ");
    move(7, 71);
    addstr(" ");
    move(8, 71);
    addstr(" ");
    move(8, 72);
    addstr(" ");
    move(9, 72);
    addstr(" ");
    move(9, 73);
    addstr(" ");

    move(8, 73);
    addstr(" ");
    move(7, 73);
    addstr(" ");
    move(6, 73);
    addstr(" ");
    move(5, 73);
    addstr(" ");
    move(9, 74);
    addstr(" ");
    move(8, 74);
    addstr(" ");
    move(7, 74);
    addstr(" ");
    move(6, 74);
    addstr(" ");
    move(5, 74);
    addstr(" ");

    attroff(COLOR_PAIR(4));
    move(14, 38);
    addstr("1.start");
    move(15, 38);
    addstr("2.exit");
    refresh();
}